apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-ojfc
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-fbnn-tenant/rhtap-demo-app/hacbs-test-project-ojfc@sha256:e8cb5826c99e3552847fb09bbc07904cc877207e77f9f77c4ff4ac23cecd8aa6
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
