apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-ojfc
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-ojfc
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-ojfc
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-ojfc
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-ojfc
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-fbnn-tenant/rhtap-demo-app/hacbs-test-project-ojfc@sha256:ad2d3c59c5ccd53aa0cebdb525db98981d3aca940af96b9ca7b34132c09fe88a
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
